version: '3.1'
services:
  app:
    container_name: users_and_rewards
    image: my_app
    build: ./
    ports:
      - "8189:8189"
    depends_on:
      - postgresqldb
    networks:
      - proxy.my-network

  postgresqldb:
    container_name: database
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5430:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=asu321
      - POSTGRES_USER=postgres
    networks:
      - proxy.my-network

networks:
  proxy.my-network:
    driver: bridge
